import AuthProvider from './context/AuthProvider'
import ChakraProviders from './context/ChakraUIProv'
import './layout.css'


export const metadata = {
  title: `JZ'S CORNER`,
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel='icon' href="/favicon.ico"/>
      </head>
      <body>
        <ChakraProviders>
          <AuthProvider>
            {children}
          </AuthProvider>
        </ChakraProviders>
      </body>
    </html>
  )
}
